apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kust2
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/VDodia/argoAssK
    targetRevision: HEAD
    path: kustomize-guestbook2
  destination:
    server: https://kubernetes.default.svc
    namespace: default